### ISSUE TITLE
Fails to build with ffmpg 8.0

### ISSUE THREAD

**Issue by lazka** [sciapp/gr#197]
```
gr-0.73.17/lib/gks/plugin/vc.c:315:7: error: call to undeclared function 'avcodec_close'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  315 |       avcodec_close(movie->cdc_ctx);
      |       ^
```

Here is the relevant deprecation: https://github.com/FFmpeg/FFmpeg/commit/1cc24d749569a42510399a29b034f7a77bdec34e

Since avcodec_free_context is called below, maybe this call can just be dropped?

**Comment by jheinen** [comment]
Thank you very much for pointing that out. We haven't tested ffmpeg 8 yet and will take a closer look at it.

**Comment by IngoMeyer441** [comment]
This issue is fixed with commit 1720943f5ecf76b067dc2950fab2d381378aaf18. Currently, it is only part of the development version, but we plan to create a new release in the near future.
